title: Thomas Lommel
email: thomas@example.com
description: >
  Embedded Systems, Product Management, Projektleitung
baseurl: ""
url: "https://thomaslommel.github.io"
theme: jekyll-theme-minimal
include:
  - assets/css/custom.css
